rmdir /s /q Droid\bin\
rmdir /s /q Droid\obj\
rmdir /s /q Droid.DohReporting\bin\
rmdir /s /q Droid.DohReporting\obj\
rmdir /s /q Droid.Hiv\bin\
rmdir /s /q Droid.Hiv\obj\
rmdir /s /q Droid.Msf\bin\
rmdir /s /q Droid.Msf\obj\
rmdir /s /q Droid.Phc\bin\
rmdir /s /q Droid.Phc\obj\
rmdir /s /q Droid.Tb\bin\
rmdir /s /q Droid.Tb\obj\
rmdir /s /q iOS\bin\
rmdir /s /q iOS\obj\
rmdir /s /q iOS.DohReporting\bin\
rmdir /s /q iOS.DohReporting\obj\
rmdir /s /q iOS.Hiv\bin\
rmdir /s /q iOS.Hiv\obj\
rmdir /s /q iOS.Msf\bin\
rmdir /s /q iOS.Msf\obj\
rmdir /s /q iOS.Phc\bin\
rmdir /s /q iOS.Phc\obj\
rmdir /s /q iOS.Tb\bin\
rmdir /s /q iOS.Tb\obj\
rmdir /s /q PCL\bin\
rmdir /s /q PCL\obj\
rmdir /s /q PCL.DohReporting\bin\
rmdir /s /q PCL.DohReporting\obj\
rmdir /s /q PCL.Hiv\bin\
rmdir /s /q PCL.Hiv\obj\
rmdir /s /q PCL.Msf\bin\
rmdir /s /q PCL.Msf\obj\
rmdir /s /q PCL.Phc\bin\
rmdir /s /q PCL.Phc\obj\
rmdir /s /q PCL.Tb\bin\
rmdir /s /q PCL.Tb\obj\

pause