//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCL.Tb {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TbResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TbResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCL.Tb.TbResources", typeof(TbResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB Clinical Guide.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Formulations.
        /// </summary>
        internal static string CalculatorAdultDsTbDosageAvailableFormulations {
            get {
                return ResourceManager.GetString("CalculatorAdultDsTbDosageAvailableFormulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage.
        /// </summary>
        internal static string CalculatorAdultDsTbDosageDosage {
            get {
                return ResourceManager.GetString("CalculatorAdultDsTbDosageDosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug.
        /// </summary>
        internal static string CalculatorAdultDsTbDosageDrug {
            get {
                return ResourceManager.GetString("CalculatorAdultDsTbDosageDrug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        internal static string CalculatorAdultDsTbDosagePhase {
            get {
                return ResourceManager.GetString("CalculatorAdultDsTbDosagePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string CalculatorAdultDsTbDosageResult {
            get {
                return ResourceManager.GetString("CalculatorAdultDsTbDosageResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult DS-TB Dosages.
        /// </summary>
        internal static string CalculatorAdultDsTbDosages {
            get {
                return ResourceManager.GetString("CalculatorAdultDsTbDosages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Drug.
        /// </summary>
        internal static string CalculatorAdultDsTbDosageSelectDrug {
            get {
                return ResourceManager.GetString("CalculatorAdultDsTbDosageSelectDrug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Phase.
        /// </summary>
        internal static string CalculatorAdultDsTbDosageSelectPhase {
            get {
                return ResourceManager.GetString("CalculatorAdultDsTbDosageSelectPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Weight Group.
        /// </summary>
        internal static string CalculatorAdultDsTbDosageSelectWeightGroup {
            get {
                return ResourceManager.GetString("CalculatorAdultDsTbDosageSelectWeightGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Tuberculosis Management Guidelines 2014..
        /// </summary>
        internal static string CalculatorAdultDsTbDosageSource {
            get {
                return ResourceManager.GetString("CalculatorAdultDsTbDosageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Dose.
        /// </summary>
        internal static string CalculatorAdultDsTbDosageTargetDose {
            get {
                return ResourceManager.GetString("CalculatorAdultDsTbDosageTargetDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Group.
        /// </summary>
        internal static string CalculatorAdultDsTbDosageWeightGroup {
            get {
                return ResourceManager.GetString("CalculatorAdultDsTbDosageWeightGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult Isoniazide Preventive Therapy.
        /// </summary>
        internal static string CalculatorAdultIsoniazidePreventiveTherapy {
            get {
                return ResourceManager.GetString("CalculatorAdultIsoniazidePreventiveTherapy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On ART Treatment.
        /// </summary>
        internal static string CalculatorAdultIsoniazidePreventiveTherapyArtTreatment {
            get {
                return ResourceManager.GetString("CalculatorAdultIsoniazidePreventiveTherapyArtTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not on ART Treatment.
        /// </summary>
        internal static string CalculatorAdultIsoniazidePreventiveTherapyArtTreatmentNot {
            get {
                return ResourceManager.GetString("CalculatorAdultIsoniazidePreventiveTherapyArtTreatmentNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string CalculatorAdultIsoniazidePreventiveTherapyManagement {
            get {
                return ResourceManager.GetString("CalculatorAdultIsoniazidePreventiveTherapyManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string CalculatorAdultIsoniazidePreventiveTherapyNo {
            get {
                return ResourceManager.GetString("CalculatorAdultIsoniazidePreventiveTherapyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string CalculatorAdultIsoniazidePreventiveTherapyResult {
            get {
                return ResourceManager.GetString("CalculatorAdultIsoniazidePreventiveTherapyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ART Treatment.
        /// </summary>
        internal static string CalculatorAdultIsoniazidePreventiveTherapySelectArtTreatment {
            get {
                return ResourceManager.GetString("CalculatorAdultIsoniazidePreventiveTherapySelectArtTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Size.
        /// </summary>
        internal static string CalculatorAdultIsoniazidePreventiveTherapySelectSize {
            get {
                return ResourceManager.GetString("CalculatorAdultIsoniazidePreventiveTherapySelectSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select if TST is available.
        /// </summary>
        internal static string CalculatorAdultIsoniazidePreventiveTherapySelectTstAvailble {
            get {
                return ResourceManager.GetString("CalculatorAdultIsoniazidePreventiveTherapySelectTstAvailble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string CalculatorAdultIsoniazidePreventiveTherapySize {
            get {
                return ResourceManager.GetString("CalculatorAdultIsoniazidePreventiveTherapySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: Unknown.
        /// </summary>
        internal static string CalculatorAdultIsoniazidePreventiveTherapySource {
            get {
                return ResourceManager.GetString("CalculatorAdultIsoniazidePreventiveTherapySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TST available.
        /// </summary>
        internal static string CalculatorAdultIsoniazidePreventiveTherapyTstAvailable {
            get {
                return ResourceManager.GetString("CalculatorAdultIsoniazidePreventiveTherapyTstAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TST not available.
        /// </summary>
        internal static string CalculatorAdultIsoniazidePreventiveTherapyTstAvailableNot {
            get {
                return ResourceManager.GetString("CalculatorAdultIsoniazidePreventiveTherapyTstAvailableNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string CalculatorAdultIsoniazidePreventiveTherapyYes {
            get {
                return ResourceManager.GetString("CalculatorAdultIsoniazidePreventiveTherapyYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI.
        /// </summary>
        internal static string CalculatorBmi {
            get {
                return ResourceManager.GetString("CalculatorBmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI = (Weight in Kilograms / (Height in Meters x Height in Meters)).
        /// </summary>
        internal static string CalculatorBmiFormula {
            get {
                return ResourceManager.GetString("CalculatorBmiFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string CalculatorBmiLength {
            get {
                return ResourceManager.GetString("CalculatorBmiLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string CalculatorBmiLengthUnit {
            get {
                return ResourceManager.GetString("CalculatorBmiLengthUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled in length is not possible.
        /// </summary>
        internal static string CalculatorBmiLengthValidationParsing {
            get {
                return ResourceManager.GetString("CalculatorBmiLengthValidationParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        internal static string CalculatorBmiMass {
            get {
                return ResourceManager.GetString("CalculatorBmiMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        internal static string CalculatorBmiMassUnit {
            get {
                return ResourceManager.GetString("CalculatorBmiMassUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled in mass is not possible.
        /// </summary>
        internal static string CalculatorBmiMassValidationParsing {
            get {
                return ResourceManager.GetString("CalculatorBmiMassValidationParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string CalculatorBmiResult {
            get {
                return ResourceManager.GetString("CalculatorBmiResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Interaction.
        /// </summary>
        internal static string CalculatorDrugInteraction {
            get {
                return ResourceManager.GetString("CalculatorDrugInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARV.
        /// </summary>
        internal static string CalculatorDrugInteractionArv {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionArv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool shows clinically significant interactions. If a medicine is not listed this does not mean there are no interactions.
        ///
        ///© Copyright 2014 National HIV HCW Hotline, Medicines Information Centre, Division of Clinical Pharmacology, Faculty of Health Sciences, University of Cape Town..
        /// </summary>
        internal static string CalculatorDrugInteractionDisclaimer {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine.
        /// </summary>
        internal static string CalculatorDrugInteractionEdl {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionEdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactions.
        /// </summary>
        internal static string CalculatorDrugInteractionInteractions {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionInteractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No interaction reported.
        /// </summary>
        internal static string CalculatorDrugInteractionInteractionsDefaultText {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionInteractionsDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string CalculatorDrugInteractionManagement {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dosage adjustment required.
        /// </summary>
        internal static string CalculatorDrugInteractionManagementDefaultText {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionManagementDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string CalculatorDrugInteractionResult {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ARV.
        /// </summary>
        internal static string CalculatorDrugInteractionSelectArv {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionSelectArv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Medicine.
        /// </summary>
        internal static string CalculatorDrugInteractionSelectEdl {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionSelectEdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDR Treatment Follow Up Date.
        /// </summary>
        internal static string CalculatorMdrTreatmentFollowUpDate {
            get {
                return ResourceManager.GetString("CalculatorMdrTreatmentFollowUpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string CalculatorMdrTreatmentFollowUpDateDate {
            get {
                return ResourceManager.GetString("CalculatorMdrTreatmentFollowUpDateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@openmedicineproject.org.
        /// </summary>
        internal static string CalculatorMdrTreatmentFollowUpDateEmailAddress {
            get {
                return ResourceManager.GetString("CalculatorMdrTreatmentFollowUpDateEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///See the attached file for the treatment dates.
        ///
        ///Regards,
        ///TB Clinical Guide.
        /// </summary>
        internal static string CalculatorMdrTreatmentFollowUpDateEmailBody {
            get {
                return ResourceManager.GetString("CalculatorMdrTreatmentFollowUpDateEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB Treatment dates.
        /// </summary>
        internal static string CalculatorMdrTreatmentFollowUpDateEmailSubject {
            get {
                return ResourceManager.GetString("CalculatorMdrTreatmentFollowUpDateEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string CalculatorMdrTreatmentFollowUpDateMessage {
            get {
                return ResourceManager.GetString("CalculatorMdrTreatmentFollowUpDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next appointment over.
        /// </summary>
        internal static string CalculatorMdrTreatmentFollowUpDateNextAppointmentOver {
            get {
                return ResourceManager.GetString("CalculatorMdrTreatmentFollowUpDateNextAppointmentOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string CalculatorMdrTreatmentFollowUpDateResult {
            get {
                return ResourceManager.GetString("CalculatorMdrTreatmentFollowUpDateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Start Date.
        /// </summary>
        internal static string CalculatorMdrTreatmentFollowUpDateSelectTreatmentDate {
            get {
                return ResourceManager.GetString("CalculatorMdrTreatmentFollowUpDateSelectTreatmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: unknown.
        /// </summary>
        internal static string CalculatorMdrTreatmentFollowUpDateSource {
            get {
                return ResourceManager.GetString("CalculatorMdrTreatmentFollowUpDateSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment started today.
        /// </summary>
        internal static string CalculatorMdrTreatmentFollowUpDateToday {
            get {
                return ResourceManager.GetString("CalculatorMdrTreatmentFollowUpDateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Date.
        /// </summary>
        internal static string CalculatorMdrTreatmentFollowUpDateTreatmentDate {
            get {
                return ResourceManager.GetString("CalculatorMdrTreatmentFollowUpDateTreatmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled in date is not possible.
        /// </summary>
        internal static string CalculatorMdrTreatmentFollowUpDateTreatmentDateValidationParsing {
            get {
                return ResourceManager.GetString("CalculatorMdrTreatmentFollowUpDateTreatmentDateValidationParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields (day, month, year) are required fields.
        /// </summary>
        internal static string CalculatorMdrTreatmentFollowUpDateTreatmentDateValidationRequired {
            get {
                return ResourceManager.GetString("CalculatorMdrTreatmentFollowUpDateTreatmentDateValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage.
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosage {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Formulations.
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosageAvailableFormulations {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosageAvailableFormulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosageCategory {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage.
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosageDosage {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosageDosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug.
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosageDrug {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosageDrug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosageDuration {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosageDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Daily Dose.
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosageMaximumDailyDose {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosageMaximumDailyDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosagePhase {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosagePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosageResult {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosageResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paediatric DS-TB Dosages.
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosages {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosageSelectCategory {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosageSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Drug.
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosageSelectDrug {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosageSelectDrug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select phase.
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosageSelectPhase {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosageSelectPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Weight Group.
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosageSelectWeightGroup {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosageSelectWeightGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidelines for the Management of Tuberculosis in Children 2014..
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosageSource {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Dose.
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosageTargetDose {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosageTargetDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Group.
        /// </summary>
        internal static string CalculatorPaediatricDsTbDosageWeightGroup {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDsTbDosageWeightGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paediatric Isoniazide Preventive Therapy.
        /// </summary>
        internal static string CalculatorPaediatricIsoniazidePreventiveTherapy {
            get {
                return ResourceManager.GetString("CalculatorPaediatricIsoniazidePreventiveTherapy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Formulations.
        /// </summary>
        internal static string CalculatorPaediatricIsoniazidePreventiveTherapyAvailableFormulations {
            get {
                return ResourceManager.GetString("CalculatorPaediatricIsoniazidePreventiveTherapyAvailableFormulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage.
        /// </summary>
        internal static string CalculatorPaediatricIsoniazidePreventiveTherapyDosage {
            get {
                return ResourceManager.GetString("CalculatorPaediatricIsoniazidePreventiveTherapyDosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string CalculatorPaediatricIsoniazidePreventiveTherapyResult {
            get {
                return ResourceManager.GetString("CalculatorPaediatricIsoniazidePreventiveTherapyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Weight Group.
        /// </summary>
        internal static string CalculatorPaediatricIsoniazidePreventiveTherapySelectWeightGroup {
            get {
                return ResourceManager.GetString("CalculatorPaediatricIsoniazidePreventiveTherapySelectWeightGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidelines for the Management of Tuberculosis in Children 2014..
        /// </summary>
        internal static string CalculatorPaediatricIsoniazidePreventiveTherapySource {
            get {
                return ResourceManager.GetString("CalculatorPaediatricIsoniazidePreventiveTherapySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target dose.
        /// </summary>
        internal static string CalculatorPaediatricIsoniazidePreventiveTherapyTargetDose {
            get {
                return ResourceManager.GetString("CalculatorPaediatricIsoniazidePreventiveTherapyTargetDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Group.
        /// </summary>
        internal static string CalculatorPaediatricIsoniazidePreventiveTherapyWeightGroup {
            get {
                return ResourceManager.GetString("CalculatorPaediatricIsoniazidePreventiveTherapyWeightGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB Treatment Follow Up Date.
        /// </summary>
        internal static string CalculatorTbTreatmentFollowUpDate {
            get {
                return ResourceManager.GetString("CalculatorTbTreatmentFollowUpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string CalculatorTbTreatmentFollowUpDateDate {
            get {
                return ResourceManager.GetString("CalculatorTbTreatmentFollowUpDateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@openmedicineproject.org.
        /// </summary>
        internal static string CalculatorTbTreatmentFollowUpDateEmailAddress {
            get {
                return ResourceManager.GetString("CalculatorTbTreatmentFollowUpDateEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///See the attached file for the treatment dates.
        ///
        ///Regards,
        ///TB Clinical Guide.
        /// </summary>
        internal static string CalculatorTbTreatmentFollowUpDateEmailBody {
            get {
                return ResourceManager.GetString("CalculatorTbTreatmentFollowUpDateEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB Treatment dates.
        /// </summary>
        internal static string CalculatorTbTreatmentFollowUpDateEmailSubject {
            get {
                return ResourceManager.GetString("CalculatorTbTreatmentFollowUpDateEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string CalculatorTbTreatmentFollowUpDateMessage {
            get {
                return ResourceManager.GetString("CalculatorTbTreatmentFollowUpDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next appointment over.
        /// </summary>
        internal static string CalculatorTbTreatmentFollowUpDateNextAppointmentOver {
            get {
                return ResourceManager.GetString("CalculatorTbTreatmentFollowUpDateNextAppointmentOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string CalculatorTbTreatmentFollowUpDateResult {
            get {
                return ResourceManager.GetString("CalculatorTbTreatmentFollowUpDateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Start Date.
        /// </summary>
        internal static string CalculatorTbTreatmentFollowUpDateSelectTreatmentDate {
            get {
                return ResourceManager.GetString("CalculatorTbTreatmentFollowUpDateSelectTreatmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: unknown.
        /// </summary>
        internal static string CalculatorTbTreatmentFollowUpDateSource {
            get {
                return ResourceManager.GetString("CalculatorTbTreatmentFollowUpDateSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment started today.
        /// </summary>
        internal static string CalculatorTbTreatmentFollowUpDateToday {
            get {
                return ResourceManager.GetString("CalculatorTbTreatmentFollowUpDateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Date.
        /// </summary>
        internal static string CalculatorTbTreatmentFollowUpDateTreatmentDate {
            get {
                return ResourceManager.GetString("CalculatorTbTreatmentFollowUpDateTreatmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled in date is not possible.
        /// </summary>
        internal static string CalculatorTbTreatmentFollowUpDateTreatmentDateValidationParsing {
            get {
                return ResourceManager.GetString("CalculatorTbTreatmentFollowUpDateTreatmentDateValidationParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields (day, month, year) are required fields.
        /// </summary>
        internal static string CalculatorTbTreatmentFollowUpDateTreatmentDateValidationRequired {
            get {
                return ResourceManager.GetString("CalculatorTbTreatmentFollowUpDateTreatmentDateValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of Health.
        /// </summary>
        internal static string SplashTextLine1 {
            get {
                return ResourceManager.GetString("SplashTextLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB Clinical Guidelines 2015.
        /// </summary>
        internal static string SplashTextLine2 {
            get {
                return ResourceManager.GetString("SplashTextLine2", resourceCulture);
            }
        }
    }
}
