//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCL {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PCLResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PCLResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCL.PCLResources", typeof(PCLResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of this application available in the Play Store. You need to install this update within 7 days to continue using this application..
        /// </summary>
        public static string ApplicationUpdateAvailable_Android {
            get {
                return ResourceManager.GetString("ApplicationUpdateAvailable_Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of this application available in the App Store. You need to install this update within 7 days to continue using this application..
        /// </summary>
        public static string ApplicationUpdateAvailable_iOS {
            get {
                return ResourceManager.GetString("ApplicationUpdateAvailable_iOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of this application available in the Play Store. You need to install this update before you can continue..
        /// </summary>
        public static string ApplicationUpdateRequired_Android {
            get {
                return ResourceManager.GetString("ApplicationUpdateRequired_Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of this application available in the App Store. You need to install this update before you can continue..
        /// </summary>
        public static string ApplicationUpdateRequired_iOS {
            get {
                return ResourceManager.GetString("ApplicationUpdateRequired_iOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculators.
        /// </summary>
        public static string Calculators {
            get {
                return ResourceManager.GetString("Calculators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for update.
        /// </summary>
        public static string CheckingForUpdate {
            get {
                return ResourceManager.GetString("CheckingForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New content available. You will need to update within 7 days..
        /// </summary>
        public static string ContentUpdateAvailable {
            get {
                return ResourceManager.GetString("ContentUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New content available. Please update before continuing..
        /// </summary>
        public static string ContentUpdateRequired {
            get {
                return ResourceManager.GetString("ContentUpdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content found to download. Please report this error to TOMPSA (info@openmedicineproject.org).
        ///
        ///ERROR_CODE: 102.
        /// </summary>
        public static string ContentUpdateUnknown {
            get {
                return ResourceManager.GetString("ContentUpdateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string DownloadLater {
            get {
                return ResourceManager.GetString("DownloadLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check if your internet connection is working..
        /// </summary>
        public static string DownloadLatestFileFailed {
            get {
                return ResourceManager.GetString("DownloadLatestFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download now.
        /// </summary>
        public static string DownloadNow {
            get {
                return ResourceManager.GetString("DownloadNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting.
        /// </summary>
        public static string Extracting {
            get {
                return ResourceManager.GetString("Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important information.
        /// </summary>
        public static string ImportantInformation {
            get {
                return ResourceManager.GetString("ImportantInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact numbers.
        /// </summary>
        public static string ItemContactContactNumbers {
            get {
                return ResourceManager.GetString("ItemContactContactNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string ItemContactEmailAddress {
            get {
                return ResourceManager.GetString("ItemContactEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility.
        /// </summary>
        public static string ItemContactFacility {
            get {
                return ResourceManager.GetString("ItemContactFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string ItemContactFacilityClassification {
            get {
                return ResourceManager.GetString("ItemContactFacilityClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string ItemContactFacilityManager {
            get {
                return ResourceManager.GetString("ItemContactFacilityManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Email.
        /// </summary>
        public static string ItemContactFacilityManagerEmailAddress {
            get {
                return ResourceManager.GetString("ItemContactFacilityManagerEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location on map.
        /// </summary>
        public static string ItemContactMap {
            get {
                return ResourceManager.GetString("ItemContactMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load map because there is no internet connection..
        /// </summary>
        public static string ItemContactMapNoInternetConnection {
            get {
                return ResourceManager.GetString("ItemContactMapNoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this location in map application.
        /// </summary>
        public static string ItemContactOpenThisLocationInMapApplication {
            get {
                return ResourceManager.GetString("ItemContactOpenThisLocationInMapApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical address.
        /// </summary>
        public static string ItemContactPhysicalAddress {
            get {
                return ResourceManager.GetString("ItemContactPhysicalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal address.
        /// </summary>
        public static string ItemContactPostalAddress {
            get {
                return ResourceManager.GetString("ItemContactPostalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string ItemContactWebsite {
            get {
                return ResourceManager.GetString("ItemContactWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working hours.
        /// </summary>
        public static string ItemContactWorkingHours {
            get {
                return ResourceManager.GetString("ItemContactWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand.
        /// </summary>
        public static string IUnderstand {
            get {
                return ResourceManager.GetString("IUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No date selected.
        /// </summary>
        public static string NoDateSelected {
            get {
                return ResourceManager.GetString("NoDateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        public static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will not be possible to send the form, because there is no internet connection..
        /// </summary>
        public static string NoInternetConnectionFormSubmit {
            get {
                return ResourceManager.GetString("NoInternetConnectionFormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you can use this application data needs to be downloaded. Please connect to the internet..
        /// </summary>
        public static string NoInternetConnectionMessage {
            get {
                return ResourceManager.GetString("NoInternetConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported.
        /// </summary>
        public static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintWebViewing not supported on this device..
        /// </summary>
        public static string PrintingNotSupported {
            get {
                return ResourceManager.GetString("PrintingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} %.
        /// </summary>
        public static string ProgressPercentage {
            get {
                return ResourceManager.GetString("ProgressPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} %.
        /// </summary>
        public static string ProgressPercentageExtended {
            get {
                return ResourceManager.GetString("ProgressPercentageExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting permissions.
        /// </summary>
        public static string RequestingPermissions {
            get {
                return ResourceManager.GetString("RequestingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After pressing &quot;Next&quot; a dialog will show up which ask your permission for storing files. This permission is required for saving the content that is used in this application. Without this permission the application cannot be used..
        /// </summary>
        public static string RequestingPermissionsMessage {
            get {
                return ResourceManager.GetString("RequestingPermissionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical information.
        /// </summary>
        public static string TechnicalInformation {
            get {
                return ResourceManager.GetString("TechnicalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing update.
        /// </summary>
        public static string UpdateCompleting {
            get {
                return ResourceManager.GetString("UpdateCompleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting update.
        /// </summary>
        public static string UpdateStarting {
            get {
                return ResourceManager.GetString("UpdateStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in at least one.
        /// </summary>
        public static string ValidationAtLeastOneResultRequired {
            get {
                return ResourceManager.GetString("ValidationAtLeastOneResultRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing error.
        /// </summary>
        public static string ValidationParsing {
            get {
                return ResourceManager.GetString("ValidationParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required error.
        /// </summary>
        public static string ValidationRequired {
            get {
                return ResourceManager.GetString("ValidationRequired", resourceCulture);
            }
        }
    }
}
