//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCL.Phc {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PhcResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PhcResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCL.Phc.PhcResources", typeof(PhcResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHC Clinical Guide.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardiovascular Event Risk.
        /// </summary>
        public static string CalculatorCardiovascularRisk {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string CalculatorCardiovascularRiskAge {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP Treatment.
        /// </summary>
        public static string CalculatorCardiovascularRiskBpTreatment {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskBpTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristics.
        /// </summary>
        public static string CalculatorCardiovascularRiskCharacteristics {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabetic.
        /// </summary>
        public static string CalculatorCardiovascularRiskDiabetic {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskDiabetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDL cholesterol.
        /// </summary>
        public static string CalculatorCardiovascularRiskHdlCholesterol {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskHdlCholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framingham tables: Klug E; South African Heart Association (S A Heart); Lipid and Atherosclerosis Society of Southern Africa (LASSA). South African dyslipidaemia guideline consensus statement. SAMJ 2012 Feb 23;102(3 Pt 2):178-87 http://www.ncbi.nlm.nih.gov/pubmed/922380916.
        /// </summary>
        public static string CalculatorCardiovascularRiskReference1 {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskReference1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framingham tables: SAHA. Update on changes to South African Dyslipidaemia Guidelines, 2012. [Online, 2012][Cited 2014] Available at: http://www.saheart.org/uploads/files/Algorithm2.pdf.
        /// </summary>
        public static string CalculatorCardiovascularRiskReference2 {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskReference2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framingham tables: Wilson PW, D&apos;Agostino RB, Levy D, Belanger AM, Silbershatz H, Kannel WB. Prediction of coronary heart disease using risk factor categories. Circulation.1998 May 12;97(18):1837-47. http://www.ncbi.nlm.nih.gov/pubmed/9603539.
        /// </summary>
        public static string CalculatorCardiovascularRiskReference3 {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskReference3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string CalculatorCardiovascularRiskResult {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient requires referral if the cholesterol is above 7.5 mmol/L..
        /// </summary>
        public static string CalculatorCardiovascularRiskResultCholesterolReferral {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskResultCholesterolReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such high-risk patients will benefit from lipid lowering (statin) therapy irrespective of their baseline LDL levels. When lipid-lowering medicines are used, this is ALWAYS in conjunction with ongoing lifestyle modification..
        /// </summary>
        public static string CalculatorCardiovascularRiskResultHighRiskPatients {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskResultHighRiskPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of Evidence: III.
        /// </summary>
        public static string CalculatorCardiovascularRiskResultLevelOfEvidence {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskResultLevelOfEvidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please always consult the complete treatment guideline found in the guidelines section of the app. The guideline on &apos;Prevention of Ischaemic Heart Disease and Atherosclerosis&apos; provides detailed information on lifestyle modification, full criteria for starting lipid lowering therapy and referral criteria..
        /// </summary>
        public static string CalculatorCardiovascularRiskResultMessage {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type 2 diabetics &gt; 40 years of age qualify for statin therapy irrespective of risk score.
        /// </summary>
        public static string CalculatorCardiovascularRiskResultOlderThan40AndDiabetic {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskResultOlderThan40AndDiabetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} % of patients with these characteristics will have a cardiovascular event i.e. death, myocardial infarction or stroke in the next 10 years..
        /// </summary>
        public static string CalculatorCardiovascularRiskResultPercentageCharacteristics {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskResultPercentageCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Age.
        /// </summary>
        public static string CalculatorCardiovascularRiskSelectAge {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskSelectAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP treatment?.
        /// </summary>
        public static string CalculatorCardiovascularRiskSelectBpTreatment {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskSelectBpTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabetic?.
        /// </summary>
        public static string CalculatorCardiovascularRiskSelectDiabetic {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskSelectDiabetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select HDL Cholesterol.
        /// </summary>
        public static string CalculatorCardiovascularRiskSelectHdlCholesterol {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskSelectHdlCholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sex.
        /// </summary>
        public static string CalculatorCardiovascularRiskSelectSex {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskSelectSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoker?.
        /// </summary>
        public static string CalculatorCardiovascularRiskSelectSmoker {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskSelectSmoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Systolic BP.
        /// </summary>
        public static string CalculatorCardiovascularRiskSelectSystolicBp {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskSelectSystolicBp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Total Cholesterol.
        /// </summary>
        public static string CalculatorCardiovascularRiskSelectTotalCholesterol {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskSelectTotalCholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string CalculatorCardiovascularRiskSex {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoker.
        /// </summary>
        public static string CalculatorCardiovascularRiskSmoker {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskSmoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: National Standard Treatment Guidelines and Essential Medicines List South Africa, 2015. Chapter  4.1 Prevention of Ischaemic Heart Disease and Atherosclerosis.
        /// </summary>
        public static string CalculatorCardiovascularRiskSource {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systolic BP.
        /// </summary>
        public static string CalculatorCardiovascularRiskSystolicBp {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskSystolicBp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cholesterol.
        /// </summary>
        public static string CalculatorCardiovascularRiskTotalCholesterol {
            get {
                return ResourceManager.GetString("CalculatorCardiovascularRiskTotalCholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICD 10 Codes.
        /// </summary>
        public static string CalculatorIcd10Codes {
            get {
                return ResourceManager.GetString("CalculatorIcd10Codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string CalculatorIcd10CodesResult {
            get {
                return ResourceManager.GetString("CalculatorIcd10CodesResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Block.
        /// </summary>
        public static string CalculatorIcd10CodesSelectBlock {
            get {
                return ResourceManager.GetString("CalculatorIcd10CodesSelectBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Chapter.
        /// </summary>
        public static string CalculatorIcd10CodesSelectChapter {
            get {
                return ResourceManager.GetString("CalculatorIcd10CodesSelectChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Code.
        /// </summary>
        public static string CalculatorIcd10CodesSelectCode {
            get {
                return ResourceManager.GetString("CalculatorIcd10CodesSelectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: World Health Organization.
        /// </summary>
        public static string CalculatorIcd10CodesSource {
            get {
                return ResourceManager.GetString("CalculatorIcd10CodesSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Costing.
        /// </summary>
        public static string CalculatorMedicineCosting {
            get {
                return ResourceManager.GetString("CalculatorMedicineCosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string CalculatorMedicineCostingBrand {
            get {
                return ResourceManager.GetString("CalculatorMedicineCostingBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract No..
        /// </summary>
        public static string CalculatorMedicineCostingContractNumber {
            get {
                return ResourceManager.GetString("CalculatorMedicineCostingContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CalculatorMedicineCostingDescription {
            get {
                return ResourceManager.GetString("CalculatorMedicineCostingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic.
        /// </summary>
        public static string CalculatorMedicineCostingGeneric {
            get {
                return ResourceManager.GetString("CalculatorMedicineCostingGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string CalculatorMedicineCostingPrice {
            get {
                return ResourceManager.GetString("CalculatorMedicineCostingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string CalculatorMedicineCostingResults {
            get {
                return ResourceManager.GetString("CalculatorMedicineCostingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Generic Name.
        /// </summary>
        public static string CalculatorMedicineCostingSelectGenericName {
            get {
                return ResourceManager.GetString("CalculatorMedicineCostingSelectGenericName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age / Weight Band.
        /// </summary>
        public static string CalculatorPaediatricDosageAgeWeightBand {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDosageAgeWeightBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose.
        /// </summary>
        public static string CalculatorPaediatricDosageDose {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDosageDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulations options.
        /// </summary>
        public static string CalculatorPaediatricDosageFormulationOptions {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDosageFormulationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string CalculatorPaediatricDosageFrequency {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDosageFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indications.
        /// </summary>
        public static string CalculatorPaediatricDosageIndications {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDosageIndications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine.
        /// </summary>
        public static string CalculatorPaediatricDosageMedicine {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDosageMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string CalculatorPaediatricDosageResult {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDosageResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paediatric Dosages.
        /// </summary>
        public static string CalculatorPaediatricDosages {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDosages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Age / Weight Band.
        /// </summary>
        public static string CalculatorPaediatricDosageSelectAgeWeightBand {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDosageSelectAgeWeightBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Medicine.
        /// </summary>
        public static string CalculatorPaediatricDosageSelectMedicine {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDosageSelectMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardised Dosage.
        /// </summary>
        public static string CalculatorPaediatricDosageStandardisedDosage {
            get {
                return ResourceManager.GetString("CalculatorPaediatricDosageStandardisedDosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of Health.
        /// </summary>
        public static string SplashTextLine1 {
            get {
                return ResourceManager.GetString("SplashTextLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Treatment Guidelines.
        /// </summary>
        public static string SplashTextLine2 {
            get {
                return ResourceManager.GetString("SplashTextLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essential Medicines List for South Africa.
        /// </summary>
        public static string SplashTextLine3 {
            get {
                return ResourceManager.GetString("SplashTextLine3", resourceCulture);
            }
        }
    }
}
