//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCL.Hiv {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HivResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HivResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCL.Hiv.HivResources", typeof(HivResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIV Clinical Guide.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adverse Reaction Pathology.
        /// </summary>
        public static string CalculatorAdverseReactionPathology {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyCalculate {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled in date is not possible.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyDateOfBirthValidationParsing {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyDateOfBirthValidationParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields (day, month, year) are required fields.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyDateOfBirthValidationRequired {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyDateOfBirthValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that abnormalities may be caused by other drugs and/or other pathology as well. Please use your clinical discretion.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyDisclaimer {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All adverse events are graded from 1 to grade 4 depending on the severity of the event as well as the age and sex of the patient. The grades are colour-coded for ease of viewing as follows: Grade 1 - green, grade 2 - yellow, grade 3 - orange, grade 4 - red. 
        ///
        ///Please consult the full guideline in the ’NDOH’ section and see the chapter on ARV drug interaction, toxicity, substitution and switching. Also be advised that symptoms alone, without abnormal blood results may indicate a severe adverse reaction. Man [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyDisclaimerPopup {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyDisclaimerPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugs potentially causing abnormalities with this laboratory value.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyDrugPotentiallyAbnormalities {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyDrugPotentiallyAbnormalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in results.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyFillInResults {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyFillInResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade 1 Mild.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyGrade1 {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyGrade1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Grade 1 Mild adverse reaction. Continue with treatment and repeat the test. Reasses the patient within 2 weeks.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyGrade1Result {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyGrade1Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade 2 Moderate.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyGrade2 {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyGrade2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Grade 2 Moderate adverse reaction. Continue with treatment and repeat the test. Reasses the patient within 2 weeks.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyGrade2Result {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyGrade2Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade 3 Severe.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyGrade3 {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyGrade3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Grade 3 Severe adverse reaction. The test must be repeated within 1 week and if it still remains at grade 3, all ARVs must be stopped and patient managed with the assistance of a specialist.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyGrade3Result {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyGrade3Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade 4 Potentially Life Threatening.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyGrade4 {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyGrade4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Grade 4 Potentially Life Threatening adverse reaction. Please consult an expert before further management. All drugs must be stopped immediately and the patient must referred to hospital. Please review the full guideline for more detailed management and how to discontinue ARVs appropriately..
        /// </summary>
        public static string CalculatorAdverseReactionPathologyGrade4Result {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyGrade4Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No abnormal adverse reaction.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyGradeNoAbnormalReaction {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyGradeNoAbnormalReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no abnormal adverse reaction..
        /// </summary>
        public static string CalculatorAdverseReactionPathologyGradeNoAbnormalReactionResult {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyGradeNoAbnormalReactionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyGrades {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyGrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyResult {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date of Birth.
        /// </summary>
        public static string CalculatorAdverseReactionPathologySelectDateOfBirth {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologySelectDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sex.
        /// </summary>
        public static string CalculatorAdverseReactionPathologySelectSex {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologySelectSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test results.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyTestResults {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test result needs to be a number.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyTestResultValidationParsing {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyTestResultValidationParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULN.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyUln {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyUln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age and sex specific Upper Limit of Normal (ULN) value used for this calculation.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyUlnNote {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyUlnNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used ULN value is {0}.
        /// </summary>
        public static string CalculatorAdverseReactionPathologyUlnUsedForCalculation {
            get {
                return ResourceManager.GetString("CalculatorAdverseReactionPathologyUlnUsedForCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARV Renal Dosage.
        /// </summary>
        public static string CalculatorArvRenalDosage {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string CalculatorArvRenalDosageAge {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string CalculatorArvRenalDosageAgeHint {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageAgeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This calculation only applies to adults. Minimum age is 15 years..
        /// </summary>
        public static string CalculatorArvRenalDosageAgeValidationOnlyForAdults {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageAgeValidationOnlyForAdults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age needs to be a number.
        /// </summary>
        public static string CalculatorArvRenalDosageAgeValidationParsing {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageAgeValidationParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age is a required field.
        /// </summary>
        public static string CalculatorArvRenalDosageAgeValidationRequired {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageAgeValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string CalculatorArvRenalDosageCalculate {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Creatinine Clearance.
        /// </summary>
        public static string CalculatorArvRenalDosageCalculateCreatinineClearance {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageCalculateCreatinineClearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cockcroft-Gault formula for estimated creatinine clearance is used for the above calculation.
        ///Formula: eCcr = ((140 - Age) * Weight (in kilograms) x Constant)) / (Serum creatinine in µmol/L)
        ///Constant: 1.23 for men and 1.04 for women..
        /// </summary>
        public static string CalculatorArvRenalDosageCalculateCreatinineClearanceDisclaimer {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageCalculateCreatinineClearanceDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated Creatinine Clearance.
        /// </summary>
        public static string CalculatorArvRenalDosageCalculatedCreatinineClearance {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageCalculatedCreatinineClearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatinine.
        /// </summary>
        public static string CalculatorArvRenalDosageCreatinine {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageCreatinine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatinine Clearance.
        /// </summary>
        public static string CalculatorArvRenalDosageCreatinineClearance {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageCreatinineClearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml/min.
        /// </summary>
        public static string CalculatorArvRenalDosageCreatinineClearanceUnit {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageCreatinineClearanceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to µmol/L.
        /// </summary>
        public static string CalculatorArvRenalDosageCreatinineHint {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageCreatinineHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatinine needs to be a number.
        /// </summary>
        public static string CalculatorArvRenalDosageCreatinineValidationParsing {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageCreatinineValidationParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatinine is a required field.
        /// </summary>
        public static string CalculatorArvRenalDosageCreatinineValidationRequired {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageCreatinineValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate Creatinine Clearance due to incorrect data.
        /// </summary>
        public static string CalculatorArvRenalDosageDataIncorrect {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageDataIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This result does not apply to children and pregnant women..
        /// </summary>
        public static string CalculatorArvRenalDosageDisclaimer {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string CalculatorArvRenalDosageResult {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Administer either the daily dose or one of the daily doses after haemodialysis.
        /// </summary>
        public static string CalculatorArvRenalDosageResultAsterisk {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageResultAsterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ARV.
        /// </summary>
        public static string CalculatorArvRenalDosageSelectArv {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageSelectArv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Dosage.
        /// </summary>
        public static string CalculatorArvRenalDosageSelectDosage {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageSelectDosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string CalculatorArvRenalDosageSex {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string CalculatorArvRenalDosageSexFemale {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageSexFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string CalculatorArvRenalDosageSexMale {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageSexMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex is a required field.
        /// </summary>
        public static string CalculatorArvRenalDosageSexValidationRequired {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageSexValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: SOUTHERN AFRICAN HIV CLINICIANS SOCIETY. Autumn 2008. Guideline for renal replacement therapy in HIV-infected individuals in South Africa..
        /// </summary>
        public static string CalculatorArvRenalDosageSource {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string CalculatorArvRenalDosageWeight {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilograms.
        /// </summary>
        public static string CalculatorArvRenalDosageWeightHint {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageWeightHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight needs to be a number.
        /// </summary>
        public static string CalculatorArvRenalDosageWeightValidationParsing {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageWeightValidationParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight is a required field.
        /// </summary>
        public static string CalculatorArvRenalDosageWeightValidationRequired {
            get {
                return ResourceManager.GetString("CalculatorArvRenalDosageWeightValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Interaction.
        /// </summary>
        public static string CalculatorDrugInteraction {
            get {
                return ResourceManager.GetString("CalculatorDrugInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARV.
        /// </summary>
        public static string CalculatorDrugInteractionArv {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionArv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool shows clinically significant interactions. If a medicine is not listed this does not mean there are no interactions.
        ///
        ///© Copyright 2014 National HIV HCW Hotline, Medicines Information Centre, Division of Clinical Pharmacology, Faculty of Health Sciences, University of Cape Town..
        /// </summary>
        public static string CalculatorDrugInteractionDisclaimer {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine.
        /// </summary>
        public static string CalculatorDrugInteractionEdl {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionEdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactions.
        /// </summary>
        public static string CalculatorDrugInteractionInteractions {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionInteractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No interaction reported.
        /// </summary>
        public static string CalculatorDrugInteractionInteractionsDefaultText {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionInteractionsDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string CalculatorDrugInteractionManagement {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dosage adjustment required.
        /// </summary>
        public static string CalculatorDrugInteractionManagementDefaultText {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionManagementDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string CalculatorDrugInteractionResult {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ARV.
        /// </summary>
        public static string CalculatorDrugInteractionSelectArv {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionSelectArv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Medicine.
        /// </summary>
        public static string CalculatorDrugInteractionSelectEdl {
            get {
                return ResourceManager.GetString("CalculatorDrugInteractionSelectEdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paediatric ARV Dosage.
        /// </summary>
        public static string CalculatorPaediatricArvDosage {
            get {
                return ResourceManager.GetString("CalculatorPaediatricArvDosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARV.
        /// </summary>
        public static string CalculatorPaediatricArvDosageArv {
            get {
                return ResourceManager.GetString("CalculatorPaediatricArvDosageArv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Formulations.
        /// </summary>
        public static string CalculatorPaediatricArvDosageAvailableFormulations {
            get {
                return ResourceManager.GetString("CalculatorPaediatricArvDosageAvailableFormulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage.
        /// </summary>
        public static string CalculatorPaediatricArvDosageDosage {
            get {
                return ResourceManager.GetString("CalculatorPaediatricArvDosageDosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string CalculatorPaediatricArvDosageResult {
            get {
                return ResourceManager.GetString("CalculatorPaediatricArvDosageResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ARV.
        /// </summary>
        public static string CalculatorPaediatricArvDosageSelectArv {
            get {
                return ResourceManager.GetString("CalculatorPaediatricArvDosageSelectArv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Weight Group.
        /// </summary>
        public static string CalculatorPaediatricArvDosageSelectWeightGroup {
            get {
                return ResourceManager.GetString("CalculatorPaediatricArvDosageSelectWeightGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: National consolidated guidelines for the prevention of mother-to-child transmission of HIV (PMTCT) and the management of HIV in children, adolescents and adults 2015. Dosages compiled by the Child and Adolescent Committee of the SA HIV Clinicians Society in collaboration with the Department of Health..
        /// </summary>
        public static string CalculatorPaediatricArvDosageSource {
            get {
                return ResourceManager.GetString("CalculatorPaediatricArvDosageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Dose.
        /// </summary>
        public static string CalculatorPaediatricArvDosageTargetDose {
            get {
                return ResourceManager.GetString("CalculatorPaediatricArvDosageTargetDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Group.
        /// </summary>
        public static string CalculatorPaediatricArvDosageWeightGroup {
            get {
                return ResourceManager.GetString("CalculatorPaediatricArvDosageWeightGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of Health.
        /// </summary>
        public static string SplashTextLine1 {
            get {
                return ResourceManager.GetString("SplashTextLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIV Clinical Guidelines 2015.
        /// </summary>
        public static string SplashTextLine2 {
            get {
                return ResourceManager.GetString("SplashTextLine2", resourceCulture);
            }
        }
    }
}
